import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { 
  Copy, 
  Download, 
  ThumbsUp, 
  ThumbsDown, 
  Clock, 
  Brain, 
  FileText,
  Youtube,
  Upload,
  ChevronDown,
  ChevronUp,
  Star,
  AlertCircle,
  CheckCircle
} from 'lucide-react';

function SummaryDisplay({ summary }) {
  const [activeTab, setActiveTab] = useState('short');
  const [expandedSections, setExpandedSections] = useState({});
  const [feedbackGiven, setFeedbackGiven] = useState(false);

  const toggleSection = (section) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const copyToClipboard = (text) => {
    navigator.clipboard.writeText(text);
    // You could add a toast notification here
  };

  const downloadSummary = () => {
    const content = `
# Summary Report

## Short Summary
${summary.summary_short}

## Medium Summary  
${summary.summary_medium}

## Detailed Summary
${summary.summary_detailed}

## Key Points
${summary.key_points.map(point => `- ${point}`).join('\n')}

${summary.query_focused_summary ? `## Query-Focused Summary\n${summary.query_focused_summary}` : ''}

---
Generated by SummarizeAI
Processing Time: ${summary.processing_time?.toFixed(2)}s
Models Used: ${summary.models_used?.join(', ')}
    `.trim();

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `summary-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleFeedback = (rating) => {
    // In a real app, you'd send this to the API
    setFeedbackGiven(true);
    console.log('Feedback:', rating);
  };

  const getConfidenceColor = (confidence) => {
    if (confidence >= 0.8) return 'confidence-high';
    if (confidence >= 0.6) return 'confidence-medium';
    return 'confidence-low';
  };

  const getConfidenceText = (confidence) => {
    if (confidence >= 0.8) return 'High Confidence';
    if (confidence >= 0.6) return 'Medium Confidence';
    return 'Low Confidence';
  };

  const getTypeIcon = () => {
    switch (summary.type) {
      case 'youtube':
        return <Youtube className="h-5 w-5 text-red-500" />;
      case 'pdf':
        return <Upload className="h-5 w-5 text-blue-500" />;
      default:
        return <FileText className="h-5 w-5 text-gray-500" />;
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="card">
        <div className="flex items-start justify-between mb-4">
          <div className="flex items-start space-x-3">
            {getTypeIcon()}
            <div>
              <h2 className="text-xl font-semibold text-gray-900">
                {summary.title || 'Summary'}
              </h2>
              <div className="flex items-center space-x-4 mt-2 text-sm text-gray-500">
                <div className="flex items-center space-x-1">
                  <Clock className="h-4 w-4" />
                  <span>{summary.processing_time?.toFixed(2)}s</span>
                </div>
                <div className="flex items-center space-x-1">
                  <Brain className="h-4 w-4" />
                  <span>{summary.models_used?.length || 1} model(s)</span>
                </div>
                {summary.confidence_scores && (
                  <div className={`flex items-center space-x-1 ${getConfidenceColor(Math.max(...summary.confidence_scores))}`}>
                    {Math.max(...summary.confidence_scores) >= 0.8 ? (
                      <CheckCircle className="h-4 w-4" />
                    ) : (
                      <AlertCircle className="h-4 w-4" />
                    )}
                    <span>{getConfidenceText(Math.max(...summary.confidence_scores))}</span>
                  </div>
                )}
              </div>
            </div>
          </div>
          
          <div className="flex space-x-2">
            <button
              onClick={() => copyToClipboard(summary[`summary_${activeTab}`])}
              className="btn-secondary flex items-center space-x-1"
              title="Copy to clipboard"
            >
              <Copy className="h-4 w-4" />
            </button>
            <button
              onClick={downloadSummary}
              className="btn-secondary flex items-center space-x-1"
              title="Download summary"
            >
              <Download className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Summary Tabs */}
        <div className="flex space-x-1 mb-4 bg-gray-100 p-1 rounded-lg">
          {['short', 'medium', 'detailed'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 rounded-md text-sm font-medium transition-colors capitalize ${
                activeTab === tab
                  ? 'bg-white text-primary-600 shadow-sm'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              {tab}
            </button>
          ))}
        </div>

        {/* Summary Content */}
        <div className="prose max-w-none">
          <ReactMarkdown className="markdown-content">
            {summary[`summary_${activeTab}`]}
          </ReactMarkdown>
        </div>
      </div>

      {/* Key Points */}
      {summary.key_points && summary.key_points.length > 0 && (
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Key Points</h3>
            <button
              onClick={() => toggleSection('keyPoints')}
              className="text-gray-400 hover:text-gray-600"
            >
              {expandedSections.keyPoints ? (
                <ChevronUp className="h-5 w-5" />
              ) : (
                <ChevronDown className="h-5 w-5" />
              )}
            </button>
          </div>
          
          {(!expandedSections.keyPoints || expandedSections.keyPoints) && (
            <ul className="space-y-2">
              {summary.key_points.map((point, index) => (
                <li key={index} className="flex items-start space-x-3">
                  <Star className="h-4 w-4 text-yellow-500 mt-0.5 flex-shrink-0" />
                  <span className="text-gray-700">{point}</span>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}

      {/* Query-Focused Summary */}
      {summary.query_focused_summary && (
        <div className="card">
          <h3 className="text-lg font-semibold text-gray-900 mb-4">
            Query-Focused Summary
          </h3>
          <div className="prose max-w-none">
            <ReactMarkdown className="markdown-content">
              {summary.query_focused_summary}
            </ReactMarkdown>
          </div>
        </div>
      )}

      {/* YouTube-specific content */}
      {summary.type === 'youtube' && summary.topic_segments && (
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Video Timeline</h3>
            <button
              onClick={() => toggleSection('timeline')}
              className="text-gray-400 hover:text-gray-600"
            >
              {expandedSections.timeline ? (
                <ChevronUp className="h-5 w-5" />
              ) : (
                <ChevronDown className="h-5 w-5" />
              )}
            </button>
          </div>
          
          {(!expandedSections.timeline || expandedSections.timeline) && (
            <div className="space-y-3">
              {summary.topic_segments.map((segment, index) => (
                <div key={index} className="border-l-4 border-primary-200 pl-4">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-sm font-medium text-primary-600">
                      {segment.timestamp}
                    </span>
                    <span className={`text-xs px-2 py-1 rounded-full ${
                      segment.importance === 'high' ? 'bg-green-100 text-green-800' :
                      segment.importance === 'medium' ? 'bg-yellow-100 text-yellow-800' :
                      segment.importance === 'low' ? 'bg-gray-100 text-gray-800' :
                      'bg-red-100 text-red-800'
                    }`}>
                      {segment.importance}
                    </span>
                  </div>
                  <div className="text-sm font-medium text-gray-900 mb-1">
                    {segment.topic}
                  </div>
                  <div className="text-sm text-gray-600">
                    {segment.summary}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* PDF-specific content */}
      {summary.type === 'pdf' && summary.document_structure && (
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">Document Structure</h3>
            <button
              onClick={() => toggleSection('structure')}
              className="text-gray-400 hover:text-gray-600"
            >
              {expandedSections.structure ? (
                <ChevronUp className="h-5 w-5" />
              ) : (
                <ChevronDown className="h-5 w-5" />
              )}
            </button>
          </div>
          
          {(!expandedSections.structure || expandedSections.structure) && (
            <div className="space-y-2">
              {summary.document_structure.map((section, index) => (
                <div key={index} className={`pl-${section.level * 4} py-2 border-l-2 border-gray-200`}>
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-gray-900">
                      {section.title}
                    </span>
                    <div className="flex items-center space-x-2 text-xs text-gray-500">
                      <span>{section.pages}</span>
                      <span>•</span>
                      <span>{section.word_count} words</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Explainability */}
      {summary.explainability && (
        <div className="card">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-lg font-semibold text-gray-900">How This Summary Was Generated</h3>
            <button
              onClick={() => toggleSection('explainability')}
              className="text-gray-400 hover:text-gray-600"
            >
              {expandedSections.explainability ? (
                <ChevronUp className="h-5 w-5" />
              ) : (
                <ChevronDown className="h-5 w-5" />
              )}
            </button>
          </div>
          
          {expandedSections.explainability && (
            <div className="space-y-4 text-sm">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <span className="font-medium text-gray-700">Method:</span>
                  <span className="ml-2 text-gray-600">{summary.explainability.method}</span>
                </div>
                <div>
                  <span className="font-medium text-gray-700">Confidence:</span>
                  <span className="ml-2 text-gray-600">{(summary.explainability.confidence * 100).toFixed(1)}%</span>
                </div>
                <div>
                  <span className="font-medium text-gray-700">Source Alignment:</span>
                  <span className="ml-2 text-gray-600">{summary.explainability.source_alignment}</span>
                </div>
                <div>
                  <span className="font-medium text-gray-700">Chunks Processed:</span>
                  <span className="ml-2 text-gray-600">{summary.explainability.chunk_count}</span>
                </div>
              </div>
              
              {summary.explainability.processing_stages && (
                <div>
                  <span className="font-medium text-gray-700 block mb-2">Processing Stages:</span>
                  <div className="flex flex-wrap gap-2">
                    {summary.explainability.processing_stages.map((stage, index) => (
                      <span key={index} className="bg-gray-100 text-gray-700 px-2 py-1 rounded text-xs">
                        {stage.replace(/_/g, ' ')}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      )}

      {/* Feedback */}
      <div className="card">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">
          How was this summary?
        </h3>
        
        {!feedbackGiven ? (
          <div className="flex items-center space-x-4">
            <button
              onClick={() => handleFeedback('positive')}
              className="flex items-center space-x-2 px-4 py-2 bg-green-50 text-green-700 rounded-lg hover:bg-green-100 transition-colors"
            >
              <ThumbsUp className="h-4 w-4" />
              <span>Helpful</span>
            </button>
            <button
              onClick={() => handleFeedback('negative')}
              className="flex items-center space-x-2 px-4 py-2 bg-red-50 text-red-700 rounded-lg hover:bg-red-100 transition-colors"
            >
              <ThumbsDown className="h-4 w-4" />
              <span>Not Helpful</span>
            </button>
          </div>
        ) : (
          <div className="text-green-600 flex items-center space-x-2">
            <CheckCircle className="h-5 w-5" />
            <span>Thank you for your feedback!</span>
          </div>
        )}
      </div>
    </div>
  );
}

export default SummaryDisplay;